### ISSUE TITLE
Turnip Crashes: Syntax Error

### ISSUE THREAD

**Issue by MisterRedstone77** [thelowsunoverthemoon/turnip#1]
Hello.

So i have been using turnip for a couple of weeks now and suddenly whenever i try to open anything made with turnip, it crashes and says: Syntax Error.

any help would be greatly appreciated,
thanks in advance.

**Comment by thelowsunoverthemoon** [comment]
Hi, I haven't changed anything. What does your code / project look like?

**Comment by MisterRedstone77** [comment]
Hello, thanks for the quick response.

So for testing this issue ive created a blank turnip project,
which without reason crashes.

Maybe ive done something wrong with the setup but even the blank project just crashes.


heres the blank project that for some reason crashes: [blank.txt](https://github.com/thelowsunoverthemoon/turnip/files/13979411/blank.txt)

**Comment by thelowsunoverthemoon** [comment]
I'm not near PC so I can't test to make sure, but it's because you have to put something inside the game loop. Since in Batch an empty FOR loop is a syntax error (which is what those variables are internally). So, you have to put REM inside as a placeholder. This is what I do for basic.bat (which is just Hello World) [here](https://github.com/thelowsunoverthemoon/turnip/blob/main/ex/Basic/basic.bat)

**Comment by MisterRedstone77** [comment]
Thank you so much for the help,
thanks to you i was finally able to pinpoint the error.

It was literally just that i cant use :: comment inside the loop.

This is for an assignment so this helped alot!

**Comment by KyleChongHengKai** [comment]
wait, if you cant use :: for comment in the game loop, how do you comment in the game loop?

**Comment by thelowsunoverthemoon** [comment]
@KyleChongHengKai Using :: in FOR loops in general lead to strange behavior. There's many ways that you can still comment though. For example, empty variables that begin with =, REM, ect cetera.

**Comment by KyleChongHengKai** [comment]
ok thanks alot!
